set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g window-size latest

set -g mouse on
set -g history-limit 10000

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -n M-n select-window -n
bind -n M-p select-window -p

setw -g mode-keys vi
set -g mouse on

# 禁用直接按 Ctrl+d 关闭窗格
bind-key -n C-d if -F '#{==:#{pane_current_command},zsh}' {
    display-message "Protected: Use Prefix+x to kill pane"
} {
    send-keys C-d
}
